 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true','--build-arg=JAR_FILE=target/messageUtil-1.0.jar']
 artifacts:
   objects:
     location: 'gs://output-bucket-codebuild/target/'
     paths: ['messageUtil-1.0.jar']